name: Hourly Job Scraper

on:
  schedule:
    # Runs every hour at minute 0
    - cron: '0 * * * *'
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a stable Node.js version compatible with Puppeteer

      - name: Install dependencies
        run: npm install

      - name: Install Puppeteer dependencies
        run: sudo apt-get update && sudo apt-get install -y libnss3 libatk-bridge2.0-0 libxkbcommon0 libgbm-dev

      - name: Run Job Scraper
        run: npm run scrape-jobs

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add data/posts.json data/scraping-metadata.json data/*.json
          git commit -m "Automated: Scraped and updated job data" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
